apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-operator
  namespace: external-secrets
spec:
  selector:
    matchLabels:
      name: external-secrets-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: external-secrets-operator
    spec:
      serviceAccountName: external-secrets-operator
      containers:
        - name: external-secrets-operator
          image: quay.io/external-secrets/kubernetes-external-secrets:v0.7.4
          command:
            - external-secrets-operator
          args:
            - --zap-level=debug
            - --zap-encoding=json
            - --zap-log-encoder=console
            - --zap-development=true
            - --zap-stacktrace-level=warn
            - --zap-locales-dir=locales
            - --zap-locales=zh,zh-CN,fr,pt-BR,en-US,ja,de,es-ES,ru,nl
            - --zap-logger=console
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secretstores.external-secrets.io
spec:
  group: external-secrets.io
  names:
    kind: SecretStore
    plural: secretstores
    singular: secretstore
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  additionalPrinterColumns:
    - name: Target
      type: string
      description: The name of the secret being created
      JSONPath: .spec.target.name
    - name: Provider
      type: string
      description: The name of the provider plugin
      JSONPath: .spec.provider.name


