---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 8b9b9392-d5e4-47b0-8c15-d84c93b3c9c1
    azure.workload.identity/tenant-id: 82913d90-8716-4025-a8e8-4f8dfa42b719
  name: external-secrets-test
  namespace: argocd
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-store
  namespace: argocd
spec:
  provider:
    azurekv:
      vaultUrl: "https://avi-key-vault.vault.azure.net/"
      serviceAccountRef:
        name: external-secrets-test
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret
  namespace: argocd
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: azure-store
    kind: ClusterSecretStore  
  target:
    name: demo-secret
    creationPolicy: Owner
  data:
  - secretKey: Cred
    remoteRef:
      key: secret/Cred
  
      
